### ISSUE TITLE
Documentation mentions using AggregationManager, which does not exist

### ISSUE THREAD

**Issue by maxispeicher** [awslabs/kinesis-aggregation#162]
The existing [README.md](https://github.com/awslabs/kinesis-aggregation/blob/master/python/README.md?plain=1#L27) for the python package and the [potential_data_loss.md](https://github.com/awslabs/kinesis-aggregation/blob/master/potential_data_loss.md?plain=1#L7) both mention using the `AggregationManager` from version `1.2.0` onwards. However, this class does not exist in the mentioned versions in the python code at all.

**Comment by tzcnt** [comment]
Has the underlying issue with the KCL dropping messages not destined for the assigned consumer been fixed? If not, then I think the documentation should have been modified, rather than deleted entirely. It's still linked from the front README with an all caps DATA LOSS CAN OCCUR. This is now a dead link.

It would be very helpful to still have an explanation of the underlying issue, even if there is no workaround.

**Comment by tzcnt** [comment]
@IanMeyers

**Comment by IanMeyers** [comment]
Documentation has been restored and corrected.
