### ISSUE TITLE
Errors when using KinesisLambdaForwarder

### ISSUE THREAD

**Issue by bodgit** [awslabs/kinesis-aggregation#17]
I've set up the KinesisLambdaForwarder to forward from one Kinesis stream to another across account boundaries. I eventually figured out the IAM pieces to the point it no longer errors about permissions but now in the CloudWatch logs I often see this:

```
Received <n> raw Kinesis records.
Received <n> deaggregated Kinesis records.
Lambda function encountered fatal error: Invalid explicitHashKey, must be greater or equal to zero and less than or equal to (2^128 - 1), got -130
```

Is this related to #11 somehow?

**Comment by geektimus** [comment]
I have a simular issue consuming data from Kinesis inside a Lambda, Basically Im using the lambda to read avro encoded events from Kinesis and send them to another stream based on the event type.

It seems that the explicitHashKey is missing on the records but it should be created using the partitionKey, but Im getting this:

`partitionKey: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -7, -126, 109, 80, 96, 74, -49, -107, 14, 84, -34, -17, -89, 84, 126], explicitHashKey: null, explicitKeyGenerated using createExplicitHashKey:-78`

 `partitionKey: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -34, -20, 60, -49, -2, -97, 79, 14, -98, -106, -106, 66, 61, 116, 43, -88], explicitHashKey: null, explicitKeyGenerated using createExplicitHashKey: -378`

The partition key is present, but the explictHashKey is negative which violates the restriction.

BTW, I think that this line is ignored on the createExplicitHashKey method:
`p.shiftLeft((16 - i - 1) * 8);` 

Because the value of the shiftLeft method is never assigned back to p.
